### ISSUE TITLE
How do I run all integ tests?

### ISSUE THREAD

**Issue by chadfords** [aumcode/nfx#18]
I want to run all integrations but apparently there are configs missing or smth. Please help as I want to check out your stripe thing

**Comment by itadapter** [comment]
@chadfords 
You will have to setup an account with Stripe or Braintree to get secret keys for your dev efforts.
Then you can set them up in the local vars roster, see the test configs for samples. The var names are in configs. One would do it the similar way with their stock drivers but would have to hard code those keys in web.config. In nfx you use $(~ENV_VAR_NAME) syntax in order not to pollute your commits into the repo

**Comment by itadapter** [comment]
closing old no-activity
