### ISSUE TITLE
Mongo lost TCP connection

### ISSUE THREAD

**Issue by chadfords** [aumcode/nfx#19]
Hey dude! I have this issue now: Mongo server gets turned off. I get a message from the closed socket and then it gets stuck as I see in log "Invalid operation" on closed socket or smth like this. What it looks like to me - something gets stuck, like a socket. I did not have time to investigate. How to reproduce:  connect to mongo using your nfx driver then tear the server down, then bring it back alive - my client app is lost now. Any help will be highly appreciated!!!! I use Mongo for high-speed queue in my project and your driver showed substantial speed-up over the "official"one provided by them

thanks,
Chad

**Comment by itadapter** [comment]
We have fixed it, let me see if it is released to GitHub yet

**Comment by itadapter** [comment]
It is fixed, the socket did indeed get stuck in Connection.cs just pull the latest code

**Comment by itadapter** [comment]
Confirmed, this was fixed and also added projection selector right to query source as discussed.
From LoadPerzonAge.mon.json, pay attention to projection element:

```
#pragma
modify=MyPerzon

{'_id': '$$id', '$NFX-QUERY-PROJECTION': {'Age': 1, '_id': 0}}
```
