### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by gregoryyoung** [aumcode/nfx#2]
Perhaps packaging things like the erlang connectivity outside of the nfx package would be reasonable?

There is a whole ton of stuff in nfx and I imagine the set of people who want to use everything in nfx does not overlap well with people who want to use erlang connectivity.

Also I noticed lack of things like SecureString is this because these are bloated or?

**Comment by itadapter** [comment]
Gregory, thanks for you comments.
This is a bit of an "UNUSUAL" project for .NET people.
NFX is a UNISTACK library, as such it is a different paradigm of:
* Design
* Architecture
* Coding/Implementation
* Team building/management
* Business operation

UNISTACK is built in such a way that everything is reusing everything else as much as possible.
One can not use Erlang out of NFX scope. Erlang currently uses configuration, application container, logging, dependency injection, starter and other key concepts of NFX.

If you want to use NFX.Erlang, deploy your NFX.DLL (which is less than 2 mbytes) and use it.
We are not planning to create packages for verticals, and Erlang support really grew naturally out of other projects that we did with NFX

As for SecureString you'll need to clarify the question. And yes, they are bloated with MS-specific stuff (much of cryptography)

**Comment by gregoryyoung** [comment]
ok thats cool I will just fork it.

Cheers and good luck with everything else.

Greg

**Comment by itadapter** [comment]
thats cool,  but I have one quick question.
If you are interested in NFX.Erlang that means that you have some net code.
If thats the case then I encourage you to look AT LEAST at the NFX.Environment.
Once you start using Configuration, especially its LACONIC format and App container, you wil forget the System.Configuration namespace for good. Thats what makes NFX central, then you also get kick-ass serializers and Glue, so why would you want to take NFX.Erlang out-of NFX.dll?

**Comment by gregoryyoung** [comment]
1) I haven't used System.Configuration in probably close to 7-8 years.
2) I rarely if ever use containers
3) I rarely work in windows (this looks highly unlikely to be portable)
4) What I need is hooking up F#/erlang
5) From looking through briefly the code is very mixed quality



On Fri, May 1, 2015 at 8:12 PM, Dmitriy@ITAdapter <notifications@github.com>
wrote:

> thats cool, but I have one quick question.
> If you are interested in NFX.Erlang that means that you have some net code.
> If thats the case then I encourage you to look AT LEAST at the
> NFX.Environment.
> Once you start using Configuration, especially its LACONIC format and App
> container, you wil forget the System.Configuration namespace for good.
> Thats what makes NFX central, then you also get kick-ass serializers and
> Glue, so why would you want to take NFX.Erlang out-of NFX.dll?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aumcode/nfx/issues/2#issuecomment-98179855>.
>



-- 
Studying for the Turing test

**Comment by itadapter** [comment]
The Erlang code is maintained by saleyn, I do not stick my nose in there.
As far as "mixed quality" comment could you please be more specific.
Please keep in mind that you are looking at C# as a coding vehicle only.
None of the .NET conventions are applicable to NFX, it is not a .NET system at all

**Comment by gregoryyoung** [comment]
What are these .net conventions you keep talking about that you seem to
hate so much? I am not familiar with them. Are you talking about asp.net or
something?

In terms of low quality errors quite a few flags immediately set me off.

1) Seemingly random usage of regions (good leading indicator of code to run
away from especially things like)

#region Constants
private const m_MyFilename = "something"
#endregion

2) Tons of util classes containing seemingly random functionality. Again
not something huge but a leading indicator

3) Went through streams code quickly, I would not accept this code through
review.

4) Singletons that I ran into. All implemented with singleton pattern
directly (e.g. not a singleton instance from a container etc) other places
accessing directly



Other areas look like they are probably quite good parsers as example ...

Keep in mind this is me going through for less than an hour nothing I have
said ensures poor quality. In general though the style/code I have been
going through screams of "legacy internal framework from the city worth
running away from" maybe for some its a good thing



On Fri, May 1, 2015 at 8:29 PM, Dmitriy@ITAdapter <notifications@github.com>
wrote:

> The Erlang code is maintained by saleyn, I do not stick my nose in there.
> As far as "mixed quality" comment could you please be more specific.
> Please keep in mind that you are looking at C# as a coding vehicle only.
> None of the .NET conventions are applicable to NFX, it is not a .NET
> system at all
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aumcode/nfx/issues/2#issuecomment-98183153>.
>



-- 
Studying for the Turing test

**Comment by itadapter** [comment]
Funny thing is, that I can say the very opposite.
"Typical Conventions":
1. all arguments need to be checked in every call - idiotic, solved with aspect injection
2. Sensless help:  .Find(): bool  returns true if found. Returns false otherwise :)
3. All files have to be justified tabified exactly the same - who said this? so you want to deprive
 all files of any personality - all looks the same 1000s of files. Dont confuse with naming conventions
4. BLOAT, BLOAT, BLOAT -  if you know linux you know how bloated the .NET stack is, a simplest thing takes 10s of files. Just garbage
5. TDD - BS. Tests are software that end user dont need. I am not in business of writing tests for tests, only to cover what I need to get the job done.



What random functionality classes are you talking about? I know everything without looking in code, and that is a good indicator of structure. StringConversions? MiscUtils? Yes there are some "broad" functions like turning a generic class name into printable format, but that is the stuff one needs often.

Ad far as "random" regions  - the regions are called and placed in the same spots in 85% of files, unless they are NOT needed.
Also the code IS PURPOSELY not tabified consistently.
That is done on PURPOSE, so while coding you can have 8 text editors open and navigate
much faster. When all code units look graphically the same - it becomes a nightmare to
visually navigate with a glance.

Where did you find a constant called an "m_" - this should not be there at all.

As far as singleton instances, could you please give me an example?
Are you talking about things like NOPApplication?

**Comment by gregoryyoung** [comment]
Funny thing is, that I can say the very opposite.

You can say the very opposite of what? I didn't say anything I asked a
question.

> "Typical Conventions":
> 1. all arguments need to be checked in every call - idiotic, solved with
> aspect injection
> 2. Sensless help: .Find(): bool returns true if found. Returns false
> otherwise :)
> 3. All files have to be justified tabified exactly the same - who said
> this? so you want to deprive
> all files of any personality - all looks the same 1000s of files. Dont
> confuse with naming conventions
> 4. BLOAT, BLOAT, BLOAT - if you know linux you know how bloated the .NET
> stack is, a simplest thing takes 10s of files. Just garbage
> 5. TDD - BS. Tests are software that end user dont need. I am not in
> business of writing tests for tests, only to cover what I need to get the
> job done.
>
> I have never seen any of these as .net conventions (except the help which
yeah forcing people to put help on things just because they are visible is
stupid).

4) give F# a try.



What random functionality classes are you talking about? I know everything
> without looking in code, and that is a good indicator of structure.
> StringConversions? MiscUtils? Yes there are some "broad" functions like
> turning a generic class name into printable format, but that is the stuff
> one needs often.
>

Lots of these "util" classes around. One of my favorites was this one
https://github.com/aumcode/nfx/blob/master/Source/NFX/IOMiscUtils.cs#L525
lots of stuff about reading bigendian then "center image".



> Ad far as "random" regions - the regions are called and placed in the same
> spots in 85% of files, unless they are NOT needed.
> Also the code IS PURPOSELY not tabified consistently.
> That is done on PURPOSE, so while coding you can have 8 text editors open
> and navigate
> much faster. When all code units look graphically the same - it becomes a
> nightmare to
> visually navigate with a glance.
>
> Where did you find a constant called an "m_" - this should not be there at
> all.
>
> As far as singleton instances, could you please give me an example?
> Are you talking about things like NOPApplication?
>
>
> How were the other 15% selected? And what is the purpose of a 2 line
region? Coming from someone who thinks having matching indentation in files
removes personality from them this is odd.

https://github.com/aumcode/nfx/blob/master/Source/NFX/Geometry/PolarPoint.cs#L67


Singleton example

https://github.com/aumcode/nfx/blob/master/Source/NFX.Web/EMail/MailerService.cs#L58
https://github.com/aumcode/nfx/blob/master/Source/NFX.Web/GeoLookup/GeoLookupService.cs#L53


Anyways mate good luck with the framework

-- 
Studying for the Turing test

**Comment by itadapter** [comment]
The 2 services that you referenced have a line of comment explicitly stating that:
"the default mailer instance" - this class is sealed and purposed for "default quick and dirty" email campaigns.
Can you show me a single practical case of making this more complex?
I just try to understand the rationale. I completely agree with you in terms of purism, but I am interested in hearing your practicality concerns

**Comment by itadapter** [comment]
As for NormalizeCentered Image - agreed, but had no better place to stick this function into.
The practicality of it is this: why create ImageUtils or something, while I don't have any other img-related.
Placed in IO because mostly this deals with re-centering user supplied images via web
