### ISSUE TITLE
How to remove old log files

### ISSUE THREAD

**Issue by AlRobo** [aumcode/nfx#20]
How I can remove old log files? Is there some attribute for it?

**Comment by itadapter** [comment]
Simple, add this job to your config root:

    event-timer
    {
        event
        {
          name="Clean Log Files"
          type="NFX.IO.FileSystem.DeleteFilesJob, NFX"
          interval="04:30:00"
          recurse=false
          delete-empty-dirs=false
          name-include-pattern="*.csv.log"
          last-modify-ago-hrs="120"
          log-stats=true

          file-system
          {
            root-path="<your log path, preferably from a variable>"
          }
        }
    }

**Comment by itadapter** [comment]
Closing old
