### ISSUE TITLE
Have you already added PDF generation stuff?

### ISSUE THREAD

**Issue by dlatushkin** [aumcode/nfx#3]

**Comment by itadapter** [comment]
We are in process of bringing this stuff in. The PDFWriter will be able to emit simple PDF pretty soon (2-3 weeks), I'll keep issue open as it is important for report/attachments in emails

**Comment by itadapter** [comment]
PDF support Merged into master under NFX.Media.PDF
See the WinFormsTest PdfTestForm for simple manual test
