### ISSUE TITLE
NLSMap - get rid of Dictionary<> for speed

### ISSUE THREAD

**Issue by cNoNim** [aumcode/nfx#31]
Use linear search instead of Dictionary<>

**Comment by itadapter** [comment]
The linear search on simple array works faster than dict[] when item count < 6.
I will think how to refactor , definitely need to get rid of dict<>

**Comment by itadapter** [comment]
# BEFORE
20170120 SEXTOD
Dictionary Optimization, 111000
Created 111,000 in 5,655 ms at 19,629 ops/sec
Occupied bytes 805,306,368
Read 111,000 in 8,468 ms at 13,142 ops/sec

# AFTER
20170120 SEXTOD
Array, Optimization, 111000
Created 111,000 in 5,200 ms at 21,387 ops/sec
Occupied bytes 805,306,368
Read 111,000 in 6,247 ms at 17,906 ops/sec

 **Write: + 8.9%**
 **Read:  +36.2%**
