### ISSUE TITLE
Samples?

### ISSUE THREAD

**Issue by alexro** [aumcode/nfx#4]
Your stuff looks interesting, would be good to have a few sample projects to play with.

**Comment by itadapter** [comment]
thanks for issue. agreed. not enough samples. we have many internally  - but they are not open sourced.

Here is where you can find SOME samples:
https://github.com/aumcode/nfx/tree/master/Source/Testing/Manual

WAVE (Web server+all web stack(MVC etc...))
https://github.com/aumcode/nfx/tree/master/Source/Testing/Manual/WaveTestSite

GLUE (Remote/distributed programming), Pile (large heaps), Cache etc...
https://github.com/aumcode/nfx/tree/master/Source/Testing/TestServer
https://github.com/aumcode/nfx/tree/master/Source/Testing/Manual/WinFormsTest (not pretty :)

and unit tests here:
https://github.com/aumcode/nfx/tree/master/Source/Testing/NUnit

However, you are right - we need to add a few "quick-start" samples

Thanks, I'll keep this issue open

**Comment by itadapter** [comment]
https://github.com/aumcode/serbench
