### ISSUE TITLE
Add trim to Slim serializer TS_refPool, as it  gets stuck after large object graph processing

### ISSUE THREAD

**Issue by itadapter** [aumcode/nfx#42]
Need to add auto-trim ability to cap the large graph.
The case when a customer serializes a huge graph - leaves the refPool with
100s of thousands of instances dangling on the heap.

Need to introduce MAX_REF_POOL_CACHE_ENTRIES and say cap at 1000 or something like this

**Comment by realisable** [comment]
Dmitriy, thank you, assuming this is the issue I logged last week.

**Comment by itadapter** [comment]
@realisable 

Add this to your app entry point (in the Main() method), before app container constructor:
`
  App.SetMemoryModel(App.MemoryUtilizationModel.Tiny);
` 

This should get rid of the buffering of references in thread pools

**Comment by itadapter** [comment]
revised, added TRIM on TLWirteSTream in  829b4a8

**Comment by itadapter** [comment]
Closing @realisable
