### ISSUE TITLE
JS Compiler: current element pointer

### ISSUE THREAD

**Issue by vlapchenko** [aumcode/nfx#50]
Please, add to JS Compiler source laconf code an ability to get a pointer to current DOM element.

**Comment by itadapter** [comment]
Provide details/example

**Comment by vlapchenko** [comment]
Example:

**Comment by OlegPanagushin** [comment]
Now you can use "$this" as point on current html element.
Also you can create pointer on any item in tree and use it:
div{
  **ljsid=root**
  div="some text" {}
  "? if(**root**.hasChild())" {
     ....
   }
}
