### ISSUE TITLE
Casting issues in NFX.Erlang

### ISSUE THREAD

**Issue by tiborebner** [aumcode/nfx#7]
The implicit cast from `ErlLong` to `int` is very dangerous and indeed led to errors in the library code. Here is a snippet from the *ErlOutputStream.cs* file which contains a bug that we discovered recently:
```CSharp
public void WriteLong(ErlLong l) { writeLong(l, l < 0); }
private void writeLong(long l, bool isNegative);
```
If `l` is positive but greater than `int.MaxValue` then the condition will evaluate to `true` meaning `l` will be serialized as a negative number (because `l` is cast to an `int` for the less-than operator). The solution is simple:
```CSharp
public void WriteLong(ErlLong l) { writeLong(l, l < 0L); }
```
I suggest you make the `ErlLong` to `int` cast explicit to avoid these subtle bugs in the library code and make clear for the users where data loss might happen on their part.

**Comment by itadapter** [comment]
Thanks, looping-in our Erl guru Serge

**Comment by saleyn** [comment]
Is implicit casting from `long` an issue or just from `int` type?  Seems like only the later.

**Comment by saleyn** [comment]
I committed this fix.

**Comment by itadapter** [comment]
I will push your fix to master tomorrow

Thanks Serge!
