### ISSUE TITLE
Move NFX Pile to separate NuGet

### ISSUE THREAD

**Issue by Nekromancer** [aumcode/nfx#76]
I would love to use your pile in our application, but it's not possible to move whole app to your framework (it's just too deep in akka.net).

Is there a possibility to get Pile as single library (apart from every other dependency from NFX Core)?

**Comment by itadapter** [comment]
@Nekromancer you **do not need to move anything in your application to NFX** to use Pile.
Just use the classes that you need (i.e. DefaultPile, Cache etc.). - **Pile works as a library without NFX framework context.**
However, at any point in future you may want to get detailed logging and instrumentation of pile - all it would take is adding a few lines in config.

**Comment by Nekromancer** [comment]
Ok, 2mb seem fare enough :) Thanks for the answer

**Comment by itadapter** [comment]
Anytime!

You can take a look here, notice there is no "NFX Frameowrk" involved, and both pile and cache work as plain library.

https://github.com/aumcode/nfx/blob/master/Source/Testing/NUnit/NFX.NUnit/AppModel/Pile/CacheTest.cs

https://github.com/aumcode/nfx/blob/master/Source/Testing/NUnit/NFX.NUnit/AppModel/Pile/PileCacheTestCore.cs#L555-L572
